# 目录设置
menu:
  Home: / || fas fa-home
  Archives: /archives/ || fas fa-archive
  Tags: /tags/ || fas fa-tags
  Categories: /categories/ || fas fa-folder-open
  List||fas fa-list:
    Music: /music/ || fas fa-music
    Movie: /movies/ || fas fa-video
  Link: /link/ || fas fa-link
  About: /about/ || fas fa-heart

# 全局设置 (确保顶格)
darkmode:
  enable: true
  button: true
highlight:
  enable: true
  copy: true
  highlight_copy: true

# 首页设置
index_img: https://chenzyishere.oss-cn-guangzhou.aliyuncs.com/img_for_typora/000027.jpg
index_layout: 3
index_post_content:
  method: 2
  length: 500

subtitle:
  enable: true
  effect: true
  source: false
  sub:
    - 量化学习驱散认知迷雾

# 全局背景图
background: https://i.loli.net/2019/09/09/5oDRkWVKctx2b6A.png

# 侧边栏头像
avatar:
  img: https://chenzyishere.oss-cn-guangzhou.aliyuncs.com/img_for_typora/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20230212223354.jpg
  effect: false

### 代码块设置
code_blocks:
  theme: darker
  macStyle: true
  height_limit: false
  word_wrap: true
  copy: true
  language: true
  shrink: false
  fullpage: true

### 文章页设置
toc:
  post: true
  page: true
  number: true
  expand: true
  style_simple: true
  scroll_percent: true

post_copyright:
  enable: true
  decode: false
  author_href: /  # 优化：不要留空，填个斜杠
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# 打赏页 (优化：如果不启用，保持 false 即可)
reward:
  enable: false

# 文章分页按钮
post_pagination: 1

# 锚点设置
anchor:
  auto_update: true
  click_to_scroll: true

footer:
  owner:
    enable: true
    since: 2025
  custom_text: 'Hi, welcome to my <a href="https://butterfly.js.org/">blog</a>!'

# 字数统计 (确保已安装 hexo-wordcount)
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true